const quotesArray = [
    "The only way to do great work is to love what you do.\n- Steve Jobs",
    "Success is not the key to happiness. Happiness is the key to success.\n- Albert Schweitzer",
    "Life is 10% what happens to us and 90% how we react to it.\n- Charles R. Swindoll",
    "The future belongs to those who believe in the beauty of their dreams.\n- Eleanor Roosevelt",
    "You miss 100% of the shots you don’t take.\n- Wayne Gretzky",
    "Success usually comes to those who are too busy to be looking for it.\n- Henry David Thoreau",
    "Don’t watch the clock; do what it does. Keep going.\n- Sam Levenson",
    "The best time to plant a tree was twenty years ago. The second best time is now.\n- Chinese Proverb",
    "Your limitation—it’s only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "The secret of getting ahead is getting started.\n- Mark Twain",
    "Life is what happens when you’re busy making other plans.\n- John Lennon",
    "Success is not in what you have, but who you are.\n- Bo Bennett",
    "You can’t build a reputation on what you are going to do.\n- Henry Ford",
    "Innovation distinguishes between a leader and a follower.\n- Steve Jobs",
    "If you can dream it, you can achieve it.\n- Zig Ziglar",
    "In the middle of every difficulty lies opportunity.\n- Albert Einstein",
    "Opportunities don't happen. You create them.\n- Chris Grosser",
    "Do not wait to strike till the iron is hot, but make it hot by striking.\n- William Butler Yeats",
    "The only limit to our realization of tomorrow will be our doubts of today.\n- Franklin D. Roosevelt",
    "Act as if what you do makes a difference. It does.\n- William James",
    "Success is not the absence of failure; it’s the persistence through failure.\n- Aisha Tyler",
    "Believe you can and you’re halfway there.\n- Theodore Roosevelt",
    "What we think, we become.\n- Buddha",
    "Your time is limited, don’t waste it living someone else’s life.\n- Steve Jobs",
    "The mind is everything. What you think you become.\n- Buddha",
    "Success is walking from failure to failure with no loss of enthusiasm.\n- Winston S. Churchill",
    "The best way to predict the future is to invent it.\n- Alan Kay",
    "Success is a journey, not a destination.\n- Arthur Ashe",
    "If you’re going through hell, keep going.\n- Winston Churchill",
    "It’s not whether you get knocked down, it’s whether you get up.\n- Vince Lombardi",
    "Life is either a daring adventure or nothing at all.\n- Helen Keller",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.\n- Ralph Waldo Emerson",
    "Believe in yourself and all that you are.\n- Christian D. Larson",
    "Success is not how high you have climbed, but how you make a positive difference to the world.\n- Roy T. Bennett",
    "Life is short, and it is up to you to make it sweet.\n- Sarah Louise Delany",
    "Your life does not get better by chance, it gets better by change.\n- Jim Rohn",
    "The only place where success comes before work is in the dictionary.\n- Vidal Sassoon",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.\n- Roy T. Bennett",
    "You are never too old to set another goal or to dream a new dream.\n- C.S. Lewis",
    "What we achieve inwardly will change outer reality.\n- Plutarch",
    "Start where you are. Use what you have. Do what you can.\n- Arthur Ashe",
    "Success is not just about what you accomplish in your life; it’s about what you inspire others to do.",
    "Your only limit is you.",
    "Be a voice, not an echo.",
    "Success is not a destination, but the road that you’re on.",
    "You can’t have a million-dollar dream with a minimum-wage work ethic.",
    "The way to get started is to quit talking and begin doing.\n- Walt Disney",
    "Motivation is what gets you started. Habit is what keeps you going.\n- Jim Ryun",
    "You don’t have to be great to start, but you have to start to be great.\n- Zig Ziglar",
    "Do what you can, with what you have, where you are.\n- Theodore Roosevelt",
    "Hardships often prepare ordinary people for an extraordinary destiny.\n- C.S. Lewis",
    "The best revenge is massive success.\n- Frank Sinatra",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is the sum of small efforts, repeated day in and day out.\n- Robert Collier",
    "It always seems impossible until it’s done.\n- Nelson Mandela",
    "If you want to lift yourself up, lift up someone else.\n- Booker T. Washington",
    "Keep your face always toward the sunshine—and shadows will fall behind you.\n- Walt Whitman",
    "Don’t be afraid to give up the good to go for the great.\n- John D. Rockefeller",
    "The only way to do great work is to love what you do.\n- Steve Jobs",
    "Change your thoughts and you change your world.\n- Norman Vincent Peale",
    "Everything you’ve ever wanted is on the other side of fear.\n- George Addair",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.\n- Winston Churchill",
    "You cannot swim for new horizons until you have courage to lose sight of the shore.\n- William Faulkner",
    "Life is what we make it, always has been, always will be.\n- Grandma Moses",
    "Life is 10% what happens to us and 90% how we react to it.",
    "The only limit to our realization of tomorrow will be our doubts of today.\n- Franklin D. Roosevelt",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.\n- Zig Ziglar",
    "Your big opportunity may be right where you are now.\n- Napoleon Hill",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.\n- Brian Tracy",
    "The future depends on what you do today.\n- Mahatma Gandhi",
    "Success is a state of mind. If you want success, start thinking of yourself as a success.\n- Joyce Brothers",
    "What you do today can improve all your tomorrows.\n- Ralph Marston"
];

export default quotesArray;
